In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [46]:
df=pd.read_csv('Churn_Modelling.csv')
X=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [47]:
#Encoding the gender column with label encoding

In [48]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [49]:
# One hot encoding for geography

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [52]:
X.shape

(10000, 12)

In [22]:
#splitting

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [25]:
#feature scaling ---> it is important to do FS for every dl model whether it is o,1 or continous number

In [54]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# Building ANN

### Initialising ANN

In [55]:
ann=tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [56]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding second hidden layer

In [57]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### adding output layer

In [58]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training an ANN

### Compile ANN

In [59]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training

In [60]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6059 - accuracy: 0.7051
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4693 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4490 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4350 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4208 - accuracy: 0.8019
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4070 - accuracy: 0.8100
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3958 - accuracy: 0.8145
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3869 - accuracy: 0.8170
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3807 - accuracy: 0.8175
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3759 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3371 - accuracy: 0.8612
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8610
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8610
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8609
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8614
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3366 - accuracy: 0.8612
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8615
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8622
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8608
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 

# Testing

In [64]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

1/1 [==============================] - 0s 54ms/step
[[False]]


In [68]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)

63/63 [==============================] - 0s 2ms/step


In [69]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [70]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [71]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_pred,y_test)
print(cm)
accuracy_score(y_pred,y_test)

[[1505  192]
 [  90  213]]


0.859